-- 코드를 입력하세요
SELECT AIN.ANIMAL_ID, AIN.ANIMAL_TYPE, AIN.NAME
FROM ANIMAL_INS AS AIN JOIN ANIMAL_OUTS AS AOUT ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID 
WHERE AIN.SEX_UPON_INTAKE LIKE '%INTACT%' AND AOUT.SEX_UPON_OUTCOME LIKE '%NEUTERED%' OR 
AIN.SEX_UPON_INTAKE LIKE '%INTACT%' AND AOUT.SEX_UPON_OUTCOME LIKE '%SPAYED%'