-- 코드를 입력하세요
SELECT AIN.NAME, AIN.DATETIME AS DATETIME 
FROM ANIMAL_INS AS AIN LEFT JOIN ANIMAL_OUTS AS AOUT
ON AIN.ANIMAL_ID = AOUT.ANIMAL_ID
WHERE AOUT.DATETIME IS NULL
ORDER BY TIMEDIFF(AOUT.DATETIME, AIN.DATETIME) DESC, DATETIME ASC
LIMIT 3