-- 코드를 입력하세요
SELECT USR.USER_ID, USR.NICKNAME, SUM(BRD.PRICE) AS TOTAL_SALES 
FROM USED_GOODS_BOARD AS BRD JOIN USED_GOODS_USER AS USR

ON BRD.WRITER_ID = USR.USER_ID 
WHERE BRD.STATUS = 'DONE'
GROUP BY USR.USER_ID
HAVING TOTAL_SALES >=700000
ORDER BY TOTAL_SALES ASC
--  서 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 결과는 총거래금액을 기준으로 오름차순 정렬해주세요. 