-- 코드를 입력하세요
SELECT CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK AS B LEFT JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE LIKE '2022-01-%'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
-- 22 26 12 9 10